@startuml

top to bottom direction
skinparam linetype ortho
skinparam ParticipantPadding 10
skinparam BoxPadding 10
skinparam Nodesep 100
skinparam Ranksep 100


class interpretador.Ambiente {
	{field} -definicoes : java.util.Map
	{field} -valores : java.util.Map
	{method} #criarSnapshot () : java.util.Map
	{method} +definirVariavel ( nome : modelos.Token , tipo : modelos.Token ) : void
	{method} +definirVariavelVetor ( nome : modelos.Token , vetor : modelos.VariavelVetor ) : void
	{method} +getTipoVariavel ( nome : modelos.Token ) : modelos.TiposToken
	{method} +getValorVariavel ( nome : modelos.Token ) : Object
	{method} +reset () : void
	{method} +setValorVariavel ( nome : modelos.Token , valor : Object ) : void
	{method} +setValorVariavelVetor ( nome : modelos.Token , index : Object , valor : Object ) : void
	{method} +setVariavelPorFuncaoLer ( nome : modelos.Token , valor : String , index : Object ) : void
}

class interpretador.ChecadorTipoEstatico { 
	{method} +castLerValor ( valor : String , tipo : modelos.TiposToken ) : Object
	{method} +castValorObject ( valor : Object ) : Object
	{method} +getTipoDoValor ( valor : Object ) : modelos.TiposToken
	{method} +isTipoValorValido ( tipo : modelos.TiposToken , valor : Object ) : boolean
}

interpretador.Ambiente -down->  interpretador.ChecadorTipoEstatico : checadorTipo

@enduml